### ISSUE TITLE
Type detection for Enlight_Controller_Action::get() broken.

### ISSUE THREAD

**Issue by bcremer** [Haehnchen/idea-php-shopware-plugin#1]
Inside controllers we use `get()` to get a service from the container. The autocompletion for the parameter works flawless but the type of the return value is not detected.

Controller:
```
$db = $this->get('db');
```

Implementation (`Enlight_Controller_Action::get()`):
```
    /**
     * Get service from resource loader
     *
     * @param string $name
     * @return mixed
     */
    public function get($name)
    {
        return $this->container->get($name);
    }
```

It would be nice if we could get that working somehow. 
We also can change the implementation of the Enlight_Controller_Action::get() if that helps.

Greetings,
Benjamin - shopware AG

**Comment by bcremer** [comment]
This behavior is unfortunately still present. Any chance to get that fixed now that https://youtrack.jetbrains.com/issue/WI-24363 is closed?

**Comment by Haehnchen** [comment]
@bcremer feature made to phpstorm9 core, now. so possibly we just need a config bridge. will check after final release.

**Comment by Haehnchen** [comment]
and the doc for this: https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata

**Comment by Haehnchen** [comment]
fixed: uhi. that was hard now. :)

fyi: Some result without shopware plugin:
![unbenannt](https://cloud.githubusercontent.com/assets/1011712/8638338/67ad1356-28b8-11e5-85e0-4bfce971b8db.png)
