### ISSUE TITLE
Add Shopware 6.1.* support

### ISSUE THREAD

**Issue by jdambacher** [Haehnchen/idea-php-shopware-plugin#113]
Shopware changed some path names etc. in the first stable release.

For example:
In SW6.1.* the path for the storefront twig files is: @Storefront/storefront/...
The plugin is still using @Storefront/...

**Comment by Haehnchen** [comment]
as i see can be fixed without plugin changes. i would say they accidentally also moved the ide-twig.json`. Moreover i guess the file is now also fully redundant and can be deleted. I will create a PR directly on the shopware platform project.

see:
https://github.com/shopware/platform/blob/6.1/src/Storefront/Resources/views/storefront/ide-twig.json

**Comment by Haehnchen** [comment]
PR create against 6.1 related on the shopware platform, to just remove the mentioned file one level up

**Comment by Haehnchen** [comment]
ref pr on shopware was merged, in additional Symfony plugin got some updates about path detection some times ago
