### ISSUE TITLE
Autocompletion for "seoUrl" twig function

### ISSUE THREAD

**Issue by dloop-mb** [Haehnchen/idea-php-shopware-plugin#119]
Please add route-type autocompletion to the first parameter of the "seoUrl" twig function from Shopware 6, just like the function "path" has.

I added manually a Method Reference to the Symfony Plugin configuration with these parameters:
```
CallTo: \Shopware\Core\Framework\Adapter\Twig\Extension\SeoUrlFunctionExtension
Method: seoUrl
Index: 0
Provider: Route
```

This works inside php but not inside twig. Could you please add this feature? Or could someone explain to me, how I can set this up manually using the Symfony plugin configuration?

Thanks!

**Comment by Haehnchen** [comment]
added in latest release
