### ISSUE TITLE
Plugin doesn't work at all

### ISSUE THREAD

**Issue by creinelt** [Haehnchen/idea-php-shopware-plugin#120]
Hello everybody,

my colleague and I installed the plugin, but none of the features work, without exception.
Symfony Plugin, PHP Annotations and PHP Toolbox are all installed and activated.
The old version of the plugin, which was only for Shopware 5, always worked for us.
Do we have to pay attention to anything else here?

My current PHPStorm version: 2021.1.2

**Comment by atty31** [comment]
I have PHPSTORM: 2022.3.1 , purchased and installed the plugin, but nothing works .. I've got no autocomplete in the twig files etc.

**Comment by Haehnchen** [comment]
Plugin is working as expected with a valid activated license; you should double check if the Symfony plugin is activated per project

![image](https://user-images.githubusercontent.com/1011712/210833633-5bebd093-cb06-4912-a9a5-8859770fe172.png)
