### ISSUE TITLE
unmaintained?

### ISSUE THREAD

**Issue by openmindculture** [Haehnchen/idea-php-shopware-plugin#128]
Is this plugin still maintained @Haehnchen ?

I have become curious because it threw an IDE(A) error after PhpStorm has updated to 2024.2 and I saw that I am still a paying customer. It's not much money, but the plugin title might mislead users to mistake it for an official Shopware plugin, while there are other recommended alternatives like Symfony Support and Shyim's Shopware toolbox that are obviously still maintained and endorsed by Shopware.

If you don't plan to maintain it further, you might consider adding appropriate notes and release it to open source for free and just display a donation link in the JetBrains store.

**Comment by Haehnchen** [comment]
many plugin need an update for 2024.2, firstly. 5.0.0 released which is api compatible.
