### ISSUE TITLE
Cache directory changed in Shopware 5.1 / ShopwareIdeMagicStuff.php

### ISSUE THREAD

**Issue by bcremer** [Haehnchen/idea-php-shopware-plugin#15]
As of Shopware 5.1 the default cache directory will be `<project>/var/cache` instead of `<project>/cache`.
We choose that to adhere to the new Symfony 3 directory structure.

Right now the Plugin creates a new file `cache/ShopwareIdeMagicStuff.php` that will be shown as unknown/new file in git.

**Comment by tiagojsag** [comment]
+1

IMO The plugin should not automatically create files inside the Shopware installation, even if it's inside the cache folder.

**Comment by Haehnchen** [comment]
i am not happy with this `ShopwareIdeMagicStuff`, but its the only possibility to provide support for magic function. as you migrating to full symfony container, i want to remove this file.
