### ISSUE TITLE
Autocompletion for engine/Shopware/Components/DependencyInjection/*.xml

### ISSUE THREAD

**Issue by mitelg** [Haehnchen/idea-php-shopware-plugin#27]
Shopware()->Container()->get('dbal'); 
autocompletion does not work anymore in this case. I can't get the dbal_connection.

I think the services mentioned in the title are not considered anymore 

PHPStorm 2016.1 and Shopware Plugin 2.1

**Comment by bcremer** [comment]
Cannot reproduce.

PHPStorm 2016.1.1
Shopware Plugin 2.1
Symfony Plugin 0.12.119

**Comment by mitelg** [comment]
okay, I can only reproduce this issue, if the project contains Shopware 5.1.x

SW 4.3.x, SW 5.0.x and SW 5.2 are working fine 

a little bit weird :confused: :question:

**Comment by bcremer** [comment]
Can also not reproduce this on SW 5.1. Have you checked that your Symfony Plugin ist active for your 5.1 directory?

**Comment by mitelg** [comment]
of course it's active... it does not work for every SW 5.1 project I have (tested 3 projects)

**Comment by Haehnchen** [comment]
@mitelg Invalid your cache or check `<service id="dbal" ... >` declarations: some synthetics or alias usages without class attribute?

**Comment by mitelg** [comment]
@Haehnchen clearing the caches works :smile: 
anyway a strange behaviour
