### ISSUE TITLE
ProviderType for \Enlight_Controller_Action::get

### ISSUE THREAD

**Issue by florianklockenkemper** [Haehnchen/idea-php-shopware-plugin#33]
Should work like Shopware()->Container()->get('xxx') that we get auto completion for methods etc. #30

**Comment by Haehnchen** [comment]
https://github.com/Haehnchen/idea-php-toolbox#types

**Comment by Haehnchen** [comment]
```
{
  "registrar":[
    {
      "provider":"symfony.services",
      "language":"php",
      "signatures":[
        {
          "class": "Enlight_Controller_Action",
          "method": "get",
          "type": "type"
        }
      ]
    }
  ]
}
```

**Comment by Haehnchen** [comment]
![screenshot from 2016-07-08 10-07-37](https://cloud.githubusercontent.com/assets/1011712/16681269/e5a5dee8-44f3-11e6-937a-ec9b1f15141c.png)
