### ISSUE TITLE
Table Name autocomplete to service shopware_attribute.crud_service

### ISSUE THREAD

**Issue by shyim** [Haehnchen/idea-php-shopware-plugin#42]
It were a nice to have feature, when we have a autocomplete to method Shopware()->Container()->get('shopware_attribute.crud_service')->update like in old method Shopware()->Models()->addAttribute :)

**Comment by Haehnchen** [comment]
Doc: https://developers.shopware.com/developers-guide/attribute-system/

**Comment by Haehnchen** [comment]
done
