### ISSUE TITLE
Add file template file for config.xml, menu.xml, cronjob.xml

### ISSUE THREAD

**Issue by shyim** [Haehnchen/idea-php-shopware-plugin#64]
Hey,
it would be awesome if we had in new file dropdown in the shopware section the config.xml etc for creation like the services.xml in the symfony plugin :)
![bildschirmfoto 2017-08-29 um 10 27 27](https://user-images.githubusercontent.com/6224096/29811710-b3b921de-8ca4-11e7-8c1c-ce62eaba17ca.png)

**Comment by mitelg** [comment]
Settings -> Editor -> File and Code Templates

Create your own ;-)

**Comment by shyim** [comment]
I can't make it in the Shopware section :P

**Comment by Haehnchen** [comment]
@shyim feel free to provide some template files you want to include :)

**Comment by shyim** [comment]
Just as plain text?

**Comment by shyim** [comment]
Created a pr for that https://github.com/Haehnchen/idea-php-shopware-plugin/pull/77
