### ISSUE TITLE
New Events aren't clickable to go to the declaration 

### ISSUE THREAD

**Issue by teiling88** [Haehnchen/idea-php-shopware-plugin#8]
![image](https://cloud.githubusercontent.com/assets/4624237/7400484/8f5dbdc2-eebd-11e4-8bde-0c829af230ed.png)

**Comment by Haehnchen** [comment]
nothing that can handle this plugin alone: https://github.com/Haehnchen/idea-php-toolbox/issues/6

**Comment by Haehnchen** [comment]
fixed by  #10
